version: '3.8'

services:

  django:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    environment:
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      FRONTEND_HOST: ${FRONTEND_HOST}
      DJANGO_EMAIL_PORT: ${DJANGO_EMAIL_PORT}
      DJANGO_EMAIL_HOST: ${DJANGO_EMAIL_HOST}
      DJANGO_EMAIL_HOST_USER: ${DJANGO_EMAIL_HOST_USER}
      DJANGO_EMAIL_HOST_PASSWORD: ${DJANGO_EMAIL_HOST_PASSWORD}
      DJANGO_EMAIL_HOST_USE_TLS: ${DJANGO_EMAIL_HOST_USE_TLS}
      DJANGO_DEFAULT_FROM_EMAIL: ${DJANGO_DEFAULT_FROM_EMAIL}
      DJANGO_SERVER_EMAIL: ${DJANGO_SERVER_EMAIL}
      CODE_VERSION: ${CODE_VERSION}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE: ${DATABASE}
    volumes:
      - ./deploy/django:/code/database # to persist sqlite database
      - ./deploy/django/collected-static:/code/collected-static
      - ./deploy/django/collected-media:/code/collected-media # to persist media files
      - ./deploy/django/logs:/code/logs
    expose:
      - "80"

  db:
    build: ./database
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PORT: ${DATABASE_PORT}
    ports:
      - "5432:5432"
    volumes:
      - ./deploy/postgres_db/:/var/lib/postgresql/data
      - ./deploy/postgres_db_dump/:/var/lib/postgresql/dump/
