version: '3.8'

services:
  django:
    build: ./backend
    restart: always
    volumes:
      - ./backend/.:/home/app/django/ # to allow django hot-reload
      - ./deploy/django/staticfiles:/home/app/django/staticfiles # to persist static files
      - ./deploy/django/mediafiles:/home/app/django/mediafiles # to persist media files
      - ./deploy/django/logs:/home/app/django/logs
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    volumes:
      - ./deploy/postgres/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PORT: ${DATABASE_PORT}

  nginx:
    build: ./nginx
    volumes:
      - ./deploy/nginx/log:/var/log/nginx # save nginx logs
      - ./deploy/django/staticfiles:/staticfiles/:ro # to serve django static content
      - ./deploy/django/mediafiles:/mediafiles/:ro # to serve django users media
    ports:
      - 8000:80
    depends_on:
      - django
