# Generated by Django 4.1.2 on 2022-10-12 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fakemodeltest',
            options={'verbose_name': 'Modelo falso de teste', 'verbose_name_plural': 'Modelo falso de testes'},
        ),
    ]
